python examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py \
    --model facebook/opt-125m \
    --dataset NeelNanda/pile-10k \
    --seed 0 \
    --quantize \
    --approach weight_only \
    --woq_algo GPTQ \
    --woq_bits 4 \
    --woq_group_size 128 \
    --gptq_pad_max_length 2048 \
    --gptq_use_max_length \
    --gptq_gpu \
    --gptq_debug