# -*- coding: utf-8 -*-
# Copyright (c) 2022 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# flake8: noqa
# mypy: ignore-errors
"""v1.14

Revision ID: 6ece06672ed3
Revises: 6f0d0f71d92e
Create Date: 2022-08-31 07:16:24.229939

"""
from sqlalchemy.orm import sessionmaker

from neural_compressor.ux.components.db_manager.db_manager import DBManager
from neural_compressor.ux.components.db_manager.db_models.optimization_type import OptimizationType
from neural_compressor.ux.components.db_manager.db_models.precision import (
    Precision,
    precision_optimization_type_association,
)
from neural_compressor.ux.utils.consts import OptimizationTypes, Precisions

db_manager = DBManager()
Session = sessionmaker(bind=db_manager.engine)


# revision identifiers, used by Alembic.
revision = "6ece06672ed3"
down_revision = "6f0d0f71d92e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with Session.begin() as db_session:
        mixed_precision_id = OptimizationType.add(
            db_session=db_session,
            name=OptimizationTypes.MIXED_PRECISION.value,
        )
        bf16_precision_id = Precision.get_precision_by_name(
            db_session=db_session,
            precision_name=Precisions.BF16.value,
        )[0]

        print("mixed_precision_id")
        print(mixed_precision_id)
        print("bf16_precision_id")
        print(bf16_precision_id)

        query = precision_optimization_type_association.insert().values(
            precision_id=bf16_precision_id,
            optimization_type_id=mixed_precision_id,
        )
        db_session.execute(query)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
