# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
from os import getenv
import importlib.util
import os
import sys
sys.path.insert(0, os.path.abspath('../../'))
moduleName = 'version'
# get version.py
modulePathNeu = os.path.abspath(os.path.join(os.getcwd(), "../.."))
modulePath = modulePathNeu + '/neural_compressor/version.py'
spec = importlib.util.spec_from_file_location(moduleName,modulePath)
NCversion = importlib.util.module_from_spec(spec)
spec.loader.exec_module(NCversion)


# -- Project information -----------------------------------------------------

project = 'Intel® Neural Compressor'
copyright = '2022, Intel® Neural Compressor'
author = 'Intel® Neural Compressor developers'

# The short X.Y version
version = NCversion.__version__
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['recommonmark', 'sphinx_markdown_tables', 'sphinx.ext.coverage', 'sphinx.ext.autosummary',
              'sphinx_md', 'autoapi.extension', 'sphinx.ext.napoleon']
autoapi_dirs = ['../../neural_compressor']
autoapi_add_toctree_entry = False
autosummary_generate = True
autoapi_options = ['members',  'show-inheritance',
                   'show-module-summary', 'imported-members', ]
autoapi_ignore = []
# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
# language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'legacy/seq2seq*']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin     themes.
#
# html_theme = "asteroid_sphinx_theme"
# html_theme = "classic"
# html_theme = "alabaster"
# html_theme = "sphinx_book_theme"
html_theme = "pytorch_sphinx_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

def skip_util_classes(app, what, name, obj, skip, options):
    if what == "class" and obj.docstring.startswith("Not displayed in API Docs.") :
       skip = True
    return skip

    
def setup(app):
    app.add_css_file("custom.css")
    app.connect("autoapi-skip-member", skip_util_classes)   

html_favicon = '_static/imgs/common/intel.svg'
# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'ProjectnameIntelLowPrecisionOptimizationTooldoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'ProjectnameIntelLowPrecisionOptimizationTool.tex', '\\textgreater{} Project name: Intel® Neural Compressor Documentation',
     'Various', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'projectnameintellowprecisionoptimizationtool', '> Project name: Intel® Neural Compressor Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'ProjectnameIntelLowPrecisionOptimizationTool', '> Project name: Intel® Neural Compressor Documentation',
     author, 'ProjectnameIntelLowPrecisionOptimizationTool', 'One line description of project.',
     'Miscellaneous'),
]


sphinx_md_useGitHubURL = True
baseBranch = "api-docs"
commitSHA = getenv('GITHUB_SHA')
githubBaseURL = 'https://github.com/' + (getenv('GITHUB_REPOSITORY') or 'intel/neural-compressor') + '/'
githubFileURL = githubBaseURL + "blob/"
githubDirURL = githubBaseURL + "tree/"
if commitSHA:
    githubFileURL = githubFileURL + commitSHA + "/"
    githubDirURL = githubDirURL + commitSHA + "/"
else:
    githubFileURL = githubFileURL + baseBranch + "/"
    githubDirURL = githubDirURL + baseBranch + "/"
sphinx_md_githubFileURL = githubFileURL
sphinx_md_githubDirURL = githubDirURL
