#
# Copyright (c) 2021 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



model:                                               # mandatory. neural_compressor uses this model name and framework name to decide where to save tuning history and deploy yaml.
  name: efficientnet_v2_b0
  framework: tensorflow                              # mandatory. supported values are tensorflow, pytorch, pytorch_ipex, onnxrt_integer, onnxrt_qlinear or mxnet; allow new framework backend extension.

device: cpu                                          # optional. default value is cpu, other value is gpu.

quantization:                                        # optional. tuning constraints on model-wise for advance user to reduce tuning space.
  calibration:
    sampling_size: 5, 10, 50, 100                    # optional. default value is the size of whole dataset. used to set how many portions of calibration dataset is used. exclusive with iterations field.
    dataloader:
      dataset:
        ImagenetRaw:
          data_path: /path/to/calibration/dataset     # NOTE: modify to calibration dataset location if needed
          image_list: /path/to/calibration/label      # data file, record image_names and their labels
      transform:
        PaddedCenterCrop:
          size: 224
          crop_padding: 32
        Resize:
          size: 224
          interpolation: bicubic
        Normalize:
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]

evaluation:                                          # optional. required if user doesn't provide eval_func in neural_compressor.Quantization.
  accuracy:                                          # optional. required if user doesn't provide eval_func in neural_compressor.Quantization.
    metric:
      topk: 1                                        # built-in metrics are topk, map, f1, allow user to register new metric.
    dataloader:
      batch_size: 32
      dataset:
        ImagenetRaw:
          data_path: /path/to/evaluation/dataset     # NOTE: modify to evaluation dataset location if needed
          image_list: /path/to/evaluation/label      # data file, record image_names and their labels
      transform:
        PaddedCenterCrop:
          size: 224
          crop_padding: 32
        Resize:
          size: 224
          interpolation: bicubic
        Normalize:
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]
  performance:                                       # optional. used to benchmark performance of passing model.
    iteration: 100
    configs:
      cores_per_instance: 4
      num_of_instance: 7
    dataloader:
      batch_size: 1
      dataset:
        ImagenetRaw:
          data_path: /path/to/evaluation/dataset     # NOTE: modify to evaluation dataset location if needed
          image_list: /path/to/evaluation/label      # data file, record image_names and their labels
      transform:
        PaddedCenterCrop:
          size: 224
          crop_padding: 32
        Resize:
          size: 224
          interpolation: bicubic
        Normalize:
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]

tuning:
  accuracy_criterion:
    relative:  0.01                                  # optional. default value is relative, other value is absolute. this example allows relative accuracy loss: 1%.
  exit_policy:
    timeout: 0                                       # optional. tuning timeout (seconds). default value is 0 which means early stop. combine with max_trials field to decide when to exit.
  random_seed: 9527                                  # optional. random seed for deterministic tuning.
