framework:                                           # mandatory. supported values are tensorflow, pytorch, or mxnet; allow new framework backend extension.
  - name: tensorflow
    inputs: input                                    # optional. inputs and outputs fields are only required in tensorflow.
    outputs: MobilenetV1/Predictions/Reshape_1

device: cpu                                          # optional. default value is cpu. other value is gpu.

dataloader:
  batch_size: 256
  dataset:
    - type: "ImageFolder"
    - root: "../imagenet/img/val" # NOTICE: config to your imagenet data path
  transform:
    Resize:
      - size: 256
    CenterCrop:
      - size: 224
    ToTensor:
    Normalize:
      - mean: [0.485, 0.456, 0.406]
      - std: [0.229, 0.224, 0.225]

calibration:                                         # optional. calibration tuning constraints on model-wise for advanced user to reduce tuning space.
  - iterations: 10, 50                               # optional. default value is 1.
    algorithm:                                       # optional. if not specified, framework built-in calibration algorithms will be used.
      - weight:  minmax
        activation: minmax
    dataloader:
      dataset:
        - root: "../imagenet/img/train" # NOTICE: config to your imagenet data path

evaluation:
  postprocess:
    transform:
      Reshape:
        - shape: [-1, 1001]

quantization:                                        # optional. tuning constraints on model-wise for advance user to reduce tuning space.
  - approach: post_training_static_quant             # optional. default value is post_training_static_quant.
    weight:
      - granularity: per_channel
        scheme: asym
        dtype: int8
    activation:
      - granularity: per_tensor
        scheme: asym
        dtype: int8

tuning:
  - strategy: basic                                  # optional. default value is basic. other values are bayesian, mse.
    metric:                                          # optional. required if user doesn't provide eval_func in ilit.tune().
      - topk: 1                                      # built-in metrics are topk, map, f1, allow user to register new metric.
    accuracy_criterion:
      - relative:  0.01                              # optional. default value is relative, other value is absolute. this example allows relative accuracy loss: 1%.
    objective: performance                           # optional. additional objectives along with accuracy constraint. default value is performance. other values are modelsize and footprint.
    timeout: 0                                       # optional. tuning timeout (seconds), default value is 0 which means early stop.
    random_seed: 9527                                # optional. random seed for deterministic tuning.
    ops: {                                           # optional. tuning constraints on op-wise for advance user to reduce tuning space. 
           'conv1': {
             'activation':  {'dtype': ['uint8', 'fp32'], 'algorithm': ['minmax', 'kl'], 'scheme':['sym']},
             'weight': {'dtype': ['int8', 'fp32'], 'algorithm': ['kl']}
           },
           'pool1': {
             'activation': {'dtype': ['int8'], 'scheme': ['sym'], 'granularity': ['per_tensor'], 'algorithm': ['minmax', 'kl']},
           },
           'conv2': {
             'activation':  {'dtype': ['fp32']},
             'weight': {'dtype': ['fp32']}
           }
         }


snapshot:                                           # optional. if not specified, snapshot will be saved under working directory.
  - path: /tmp/snapshot
