model:                                               # mandatory. ilit uses this model name and framework name to decide where to save tuning history and deploy yaml.
  name: ssd_resnet34
  framework: tensorflow                              # mandatory. supported values are tensorflow, pytorch, or mxnet; allow new framework backend extension.
  inputs: image
  outputs: detection_bboxes,detection_scores,detection_classes

quantization:                                        # optional. tuning constraints on model-wise for advance user to reduce tuning space.
  calibration:
    sampling_size: 10, 50, 100, 200                  # optional. default value is the size of whole dataset. used to set how many portions of calibration dataset is used. exclusive with iterations field.
    dataloader:                                      # optional. if not specified, user need construct a q_dataloader in code for ilit.Quantization.
      batch_size: 1
      dataset:
        COCORaw:
          root: /path/to/calibration/dataset         # NOTE: modify to coco2017 validation raw image folder
      transform:
        ImageTypeParse:
        Rescale:
        Normalize:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
        Resize:
          size: 1200
        Transpose:
          perm: [2, 0, 1]
  model_wise:                                        # optional. tuning constraints on model-wise for advance user to reduce tuning space.
    activation:
      algorithm: minmax
    weight:
      algorithm: minmax

evaluation:                                          # optional. used to config evaluation process.
  accuracy:                                          # optional. required if user doesn't provide eval_func in ilit.Quantization.
    metric: 
      COCOmAP: 
        anno_path: /path/to/annotation
    configs:                                         # optional. if not specified, use all cores in 1 socket.
      cores_per_instance: 28
      num_of_instance: 1
      kmp_blocktime: 1
    dataloader:                                      # optional. if not specified, user need construct a q_dataloader in code for ilit.Quantization.
      batch_size: 1
      dataset:
        COCORaw:
          root: /path/to/evaluation/dataset          # NOTE: modify to coco2017 validation raw image datafolder
      transform:
        ImageTypeParse:
        Rescale:
        Normalize:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
        Resize:
          size: 1200
        Transpose:
          perm: [2, 0, 1]
  performance:
    iteration: 100
    configs:
      cores_per_instance: 28
      num_of_instance: 1
      kmp_blocktime: 1
    dataloader:
      batch_size: 1
      dataset:
        COCORaw:
          root: /path/to/evaluation/dataset
      transform:
        ImageTypeParse:
        Rescale:
        Normalize:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
        Resize:
          size: 1200
        Transpose:
          perm: [2, 0, 1]
    
tuning:
  accuracy_criterion:
    relative:  0.04                                  # optional. default value is relative, other value is absolute. this example allows relative accuracy loss: 1%.
  exit_policy:
    timeout: 0                                       # optional. tuning timeout (seconds). default value is 0 which means early stop. combine with max_trials field to decide when to exit.
  random_seed: 9527                                  # optional. random seed for deterministic tuning.
